export const SCREENNAME = {

    // Tab navigation
    SHOP_SCREEN: "SHOP_SCREEN",
    PROFILE_SCREEN: "PROFILE_SCREEN",
    WISHLIST_SCREEN: "WISHLIST_SCREEN",
    CART_SCREEN: "CART_SCREEN",
    HOME_SCREEN: "HOME_SCREEN",
    CONTACT_SCREEN : "CONTACT_SCREEN",

    //Stack navigation
    EDIT_PROFILE_SCREEN: "EDIT_PROFILE_SCREEN",
    PROFILE_PAGE: "PROFILE_PAGE",
     HOME_STACK: "HOME_STACK",
    LOGIN_SCREEN: "LOGIN_SCREEN",
    WEBVIEW_CHECKOUT_SCREEN: "WEBVIEW_CHECKOUT_SCREEN",
    WEBVIEW_MAP_SCREEN: "WEBVIEW_MAP_SCREEN",
    HISTORY_SCREEN: "HISTORY_SCREEN",
    DELIVERY_STATUS_SCREEN: "DELIVERY_STATUS_SCREEN",
    DETAIL_PRODUCT_SCREEN: "DETAIL_PRODUCT_SCREEN",
    FORGOT_PASSWORD_SCREEN: "FORGOT_PASSWORD_SCREEN",
    PAYMENT_SCREEN: "PAYMENT_SCREEN",
    REGISTER_SCREEN:  "REGISTER_SCREEN",
    GROMMING_SCREEN: "GROMMING_SCREEN",
    CLEANING_SCREEN: "CLEANING_SCREEN",
    //Drawer
    HOME_DRAWER: "HOME_DRAWER",
    CATEGORY_DRAWER: "CATEGORY_DRAWER",
}

export const fonts = {
    font16: 16,
    font14: 14,
    font15: 15,
    font12: 12,
    font17: 17,
    font18: 18,
    font19: 19,
    font20: 20,
    font21: 21,
    font22: 22,
    font23: 23,
    font24: 24,
    font26: 26,
    font28: 28,
    font32: 32,
    font30: 30,
    font36: 36,
    font40: 40,
    font42: 42
}